aiuts/urls.py
from django.urls import path

from . import views

app_name = 'aiuts'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('dashboard', views.Dashboard.as_view(), name="dashboard"),
    path('dashboard/top_up', views.TopupView.as_view(), name="topup_req"),
    path('dashboard/loading', views.getRandomData, name="loading"),
    path('sign_up', views.SignupView.as_view(), name='signup'),
    path('sign_up/submit', views.create_acc, name='create_acc'),
    path('send_money', views.send_money, name='sendmoney'),
    path('deposit_money', views.deposit_money, name="depositmoney"),
    # path('account/summary/check', views.get_summary_of_transaction, name="getsummaryoftransaction"),
    path('dashboard/summary', views.TransactionSummary.as_view(), name="transactionsummary"),
    path('admin/dashboard', views.AdminDashboard.as_view(), name='admindash'),
    path('admin/dashboard/approve/<str:tid>', views.approve_transaction, name="approvetransaction"),
    path('admin/dashboard/decline/<str:tid>', views.decline_transaction, name="declinetransaction")
]

transactionsystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('aiuts/', include('aiuts.urls'))
]

aiuts/models.py
from django.db import models
from django.contrib.auth.models import User
import hashlib
# Create your models here.


class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    acc_id = models.CharField(max_length=256, primary_key=True)
    balance = models.FloatField(default=0.01)
    
    def __str__(self):
        return "{}".format(self.acc_id)

class Transaction(models.Model):
    sender = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='sender')
    recipient = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='recipient')
    amount = models.FloatField(null=False, blank=False)
    remark = models.CharField(max_length=256, default="No message")
    record_date = models.DateTimeField('date recorded', auto_now_add=True)
    complete = models.BooleanField(default=False)
    type = models.CharField(choices=[('Top Up', 'TU'), ('Request of Payment', 'ROP'), ('Normal Transaction', 'NOR')], default='Normal Transaction', max_length=20)
    id = models.AutoField(primary_key=True)

    def __str__(self):
        return "Sender: {}, Recipient: {}, Amount: {}, Date: {}, Remark: {}".format(self.sender, self.recipient, self.amount, self.record_date, self.remark)
  
# class Pending(models.Model):
#     Transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE)
#     Transaction_choices = [ ('TU','Top Up'), ('ROP','Request of Payment')]
#     Type = models.CharField(
#         choices = Transaction_choices,
#         default = "Not fill",
#         max_length = 256
#     )
#     Complete_status = models.BooleanField(default=False)

aiuts/forms.py
from .models import Transaction, Account
from django import forms
import datetime

class TopupForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account', " ")
        super(TopupForm, self).__init__(*args, **kwargs)
        self.fields['sender'].choices = [(
            Account.objects.filter(acc_id='bd5af1f610a12434c9128e4a399cef8a')[0], 'bank')]
        self.fields['recipient'].choices = [(self.account[0], 'You')]
        self.fields['amount'].widget.attrs.update({
            'step': "0.01",
            'value': 0.01 ,
            'min': 0.00,

        })
        self.fields['type'].choices = [("Top Up", "Top Up")]
        self.fields['type'].widget.attrs.update({
            'value': 'Top Up',
        })
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })
    class Meta:
        model = Transaction
        fields = ('sender', 'amount', 'recipient', 'type')

aiuts/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.template import loader
from django.views import generic
from django.contrib.auth.models import User
from .models import Account, Transaction
from django.utils import timezone
from random import random
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate
from datetime import datetime, timedelta
import hashlib
from django.http import JsonResponse
from django.core import serializers
from .forms import TopupForm

class TopupView(LoginRequiredMixin, generic.CreateView):
    login_url = '/accounts/login'
    form_class = TopupForm
    template_name = "aiuts/top_up.html"

    def get(self, *args, **kwargs):
        acc = Account.objects.filter(user=self.request.user)
        form = self.form_class(account=acc)
        curr_acc = Account.objects.get(user=self.request.user)
        bank = Account.objects.get(acc_id="bd5af1f610a12434c9128e4a399cef8a")
        transactions = Transaction.objects.filter(complete=False).filter(sender=bank)
        context = {"form": form, "all_transaction": transactions,
                   "user":curr_acc,
                   "bank": Account.objects.get(acc_id="bd5af1f610a12434c9128e4a399cef8a")}
        return render(self.request, self.template_name, context)

    def post(self, *args, **kwargs):
        if self.request.is_ajax and self.request.method == "POST":
            form = self.form_class(self.request.POST)
            if form.is_valid():
                instance = form.save()
                ser_instance = serializers.serialize('json', [instance,])
                return JsonResponse({"instance": ser_instance}, status=200)
            else:
                return JsonResponse({"error":""}, status=400)

def checkTopupReq(request):
    if request.is_ajax and request.method == "GET":
        return JsonResponse({"valid": True}, status=200)

def getRandomData(request):
    # request should be ajax and method should be GET.
    if request.is_ajax and request.method == "GET":
        now = str(timezone.now())
        return JsonResponse({"randomdata":str(hashlib.md5(now.encode()))+" - "+now}, status = 200)
    return JsonResponse({}, status = 400)

class IndexView(generic.ListView):
    template_name = 'aiuts/index.html'
    context_object_name = 'all_user'
    
    def get_queryset(self):
        """Return the last five published questions."""
        return Account.objects.all()[:]

class SignupView(generic.TemplateView):
    template_name = 'aiuts/sign_up.html'


class AdminDashboard(LoginRequiredMixin, generic.ListView):
    login_url = '/accounts/login'
    template_name = 'aiuts/admin_dash.html'
    model = Transaction
    context_object_name = 'all_transaction'

    def get_queryset(self):
        return Transaction.objects.filter(complete=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = Account.objects.get(user=self.request.user)
        return context
    

class Dashboard(LoginRequiredMixin, generic.ListView):
    login_url = '/accounts/login'
    template_name = 'aiuts/account_dash.html'
    model = Transaction
    context_object_name = 'all_transaction'

    def get_queryset(self):
        curr_acc = Account.objects.get(user=self.request.user)
        return set(Transaction.objects.filter(complete=False).filter(sender=curr_acc)).union(set(Transaction.objects.filter(complete=False).filter(recipient=curr_acc)))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = Account.objects.get(user=self.request.user)
        return context
    
    def post(self, request, *args, **kwargs):
        template = loader.get_template(self.template_name)
        user_acc = Account.objects.get(user=request.user)
        amount = float(request.POST['amount'])
        sender_addr = request.POST['acc_addr']
        if amount < 0:
            messages.info(request, "Please enter appropriate amount")
            return redirect(request.META['HTTP_REFERER'])
        if len(sender_addr):
            sender = Account.objects.get(acc_id = sender_addr)
            req_user = Transaction(sender=sender, recipient=user_acc, amount=amount, type="Request of Payment")
            req_user.save()
        messages.info(request, "New pending request is created!")
        return redirect(request.META['HTTP_REFERER'])

class TransactionSummary(LoginRequiredMixin, generic.ListView):
    login_url = '/accounts/login'
    template_name = 'aiuts/get_summary.html'
    context_object_name = 'user'

    def get_queryset(self):
        curr_user = Account.objects.get(user=self.request.user)
        acc_id = curr_user.acc_id
        return acc_id

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        curr_user = Account.objects.get(user=self.request.user)
        acc_id = curr_user.acc_id
        context['all_transaction'] = set(Transaction.objects.filter(sender=curr_user)).union(set(Transaction.objects.filter(recipient=curr_user)[:]))
        return context

    def post(self, request, *args, **kwargs):
        template = loader.get_template(self.template_name)
        user_acc = Account.objects.get(user=request.user)
        acc_addr = request.POST['acc_addr']
        from_date = request.POST['from_date']
        to_date = request.POST['to_date']
        if len(to_date):
            to_date = datetime.strptime(to_date, '%Y-%m-%d') + timedelta(days=1)
        else:
            to_date = datetime.now()
        if len(from_date) and not len(acc_addr):
            from_date = datetime.strptime(from_date, '%Y-%m-%d')
            filter_record = set(Transaction.objects.filter(sender=user_acc.acc_id).filter(record_date__range=(from_date, to_date))).union(set(Transaction.objects.filter(recipient=user_acc.acc_id).filter(record_date__range=(from_date, to_date)))) 
        else:
            filter_record = set(Transaction.objects.filter(sender=user_acc.acc_id).filter(record_date__lte=to_date)).union(set(Transaction.objects.filter(recipient=user_acc.acc_id).filter(record_date__lte=to_date))) 
        if Account.objects.filter(acc_id=acc_addr).exists():
            target_acc = Account.objects.get(acc_id=acc_addr)
            at_sender = Transaction.objects.filter(sender=user_acc)
            at_recipient = Transaction.objects.filter(recipient=user_acc)
            filter_at_sender = at_sender.filter(recipient=target_acc)
            filter_at_recipient = at_recipient.filter(sender=target_acc)
            if from_date and to_date:
                filter_at_sender = filter_at_sender.filter(record_date__range=(from_date, to_date))
                filter_at_recipient = filter_at_recipient.filter(record_date__range=(from_date, to_date))
            if not from_date:
                filter_at_sender = filter_at_sender.filter(record_date__lte=to_date)
                filter_at_recipient = filter_at_recipient.filter(record_date__lte=to_date)
            filter_record = set(filter_at_sender).union(set(filter_at_recipient))
        context = {'all_transaction':filter_record, "user":user_acc.acc_id}
        messages.info(request, "Found {} record(s)".format(len(filter_record)))
        return HttpResponse(template.render(context, request))


def create_acc(request):
    username = request.POST['username']
    password = request.POST['password']
    if not len(username) or not len(password):
        messages.info(request, 'Provide appropriate your full name and password!')
        return HttpResponseRedirect(reverse('aiuts:signup'))
    acc_id = hashlib.md5(str.encode(username)).hexdigest()
    user = User.objects.create_user(username=username, password=password)
    user.save()
    account = Account(user=user, acc_id=acc_id, balance=random() * 100)
    account.save()
    messages.info(request, '{} has been created!'.format(acc_id))
    return HttpResponseRedirect(reverse('aiuts:index'))


def send_money(request):
    acc_id = request.POST['source']
    recipient = request.POST['destination'].strip()
    amount = float(request.POST['amount'])
    password = request.POST['password']
    remark = request.POST['remark'] 
    if Account.objects.filter(acc_id=recipient).exists():
        rec_acc = Account.objects.get(acc_id=recipient)
        user = authenticate(request, username=request.user.username, password=password)
        if user is not None:
            curr_acc = Account.objects.get(acc_id=acc_id)
            if amount > 0 and amount < curr_acc.balance:
                curr_acc.balance -= amount
                rec_acc.balance += amount
                curr_acc.save()
                rec_acc.save()
                transaction = Transaction(sender=curr_acc, recipient=rec_acc, amount=amount, remark=remark, complete=True)
                transaction.save()     
                messages.info(request, "You have sent {:.2f} baht to {}".format(amount, rec_acc.user.username))
                return redirect(request.META['HTTP_REFERER'])
    messages.info(request, "Please double check the detail again")
    return redirect(request.META['HTTP_REFERER'])

def deposit_money(request):
    acc_id = request.POST['acc_id']
    amount = float(request.POST['amount'])
    password = request.POST['password']
    user = authenticate(request, username=request.user.username, password=password)
    if amount > 0:
        if user is not None:
            curr_acc = Account.objects.get(user=request.user)
            curr_acc.balance += amount
            curr_acc.save()
            trans_record = Transaction(sender=curr_acc, recipient=curr_acc, amount=amount, remark="Deposit money")
            trans_record.complete=True
            trans_record.save()

aiuts/templates/aiuts/account_dash.html
{% extends "aiuts/base.html" %}
{% block currPage %} <a href="{% url 'aiuts:index' %}"> Index </a> > Dashboard {% endblock %}
{% block title %} Dashboard {% endblock %}
{% block mainbody %}
    <hr />
    <div>
        <p style="float: left"> <b>Acc ID:</b> {{ user.acc_id}} </p>
        <div />
            <p style="float: right"> <b>Balance:</b> <span id="curr_balance">{{ user.balance | floatformat:2 }}</span> Baht </p>
        </div>
        <br />
        <h2 class="margin-top"> Pending transactions </h2>
        <hr />
        {% if all_transaction %}
            <table class="table">
                <tr> 
                    <th scope="col"> Date </th scope="col">
                    <th scope="col"> Requested </th scope="col">
                    <th scope="col"> Amount </th scope="col">

                    <th scope="col"> Type of Transaction</th>
                    <th scope="col"> Completion </th>
                </tr>
                </thead>
                <tbody>
                {% endif %}
                {% for transaction in all_transaction %}
                    <tr>
                        <th scope="row"> {{ transaction.record_date }} </th>
                    <td>{% if transaction.sender.user.username == "bank" %} {{ transaction.recipient.user.username }} {% else %} {{transaction.sender.user.username}} {% endif %}</td>
                    <td> {{ transaction.amount|floatformat:2}} Baht </td>
                    <td> {{transaction.type}}</td>

                <td>{% if transaction.recipient.user.username == request.user.username %} {{ transaction.complete }} {% else  %} <a href="{% url 'aiuts:approvetransaction' transaction.id %}"> Approve </a> | <a href="{% url 'aiuts:declinetransaction' transaction.id %}" class="text-danger"> Decline </a>{% endif %} </td>
                    </tr>
                {% empty %}
                    No pending top up request!
                {% endfor %}
                </tbody>
            </table>



            <h2 class="margin-top"> Top Up </h2>
            <hr />
            <a href="{% url 'aiuts:topup_req' %}"> Open Top Up Account </a>
            <br />
            <h2 class="margin-top"> Request Payment </h2>
            <hr />
            <form id="req_payment">
                {% csrf_token %}
                <div class="form-group">
                    <label> <b> From </b> Account Address: </label>
                    <input type="text" class="form-control" name="acc_addr" />
                    <label> Amount: </label>
                    <input class="form-control" required="required" type="number" step="0.01" name="amount">

                    <input class="btn my-2 btn-outline-primary" type="submit" value="Request">
                </div>

            </form>


            <h2 class="margin-top"> Send Money </h2>
            <hr />
            <form id="send_payment">
                {% csrf_token %}
                <div class="form-group">
                    <input type="hidden" name="source" value="{{ user.acc_id }}"/>
                    <label> Recipient Acc_id: </label>
                    <input required="required" type="text" class="form-control" name="destination" placeholder="asdf2323r234rawf23f">
                    <label> Amount: </label>
                    <input class="form-control" required="required" type="number" min="0" max="{{ user.balance }}"
                                                                                          step="0.01" name="amount">
                </div>
                <div class="form-group">
                    <label for="password">Password: </label>
                    <input required="required" class="form-control" type="password" name="password" />
                </div>
                <label> Remark: </label>
                <textarea name="remark" class="form-control"></textarea>

                <input type="submit" value="Send" class="btn btn-outline-primary my-1">
            </form>



            <h2 class="margin-top"> Get Summary's Transaction </h2>
            <hr />
            <a href="{% url 'aiuts:transactionsummary' %}"> Open Summary of Transaction </a>





        {% endblock %}
        {% block script %}
            $("#send_payment").submit(function (e) {
            e.preventDefault();
            var serializedData = $(this).serialize();
            $.ajax({
            type: 'POST',
            url: "{% url 'aiuts:sendmoney' %}",
            data: serializedData,
            success: function (response) {
            $("#send_payment").trigger('reset');
            alert = `<ul class="messages">
                <div class="position-fixed bg-white border font-weight-bold border-dark alert alert-white alert-dismissible fade show" style="top: 10px; right: 1vw;" role="alert">
                    Sending completed!
                    <a type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </a>
                </div>

            </ul>`;
            $(".messages").hide();
            $("body").append(alert);
            setTimeout(function() {$(".messages").hide()}, 2000)

            },
            error: function(response) {

            }
            })
            })
            $("#req_payment").submit(function (e) {
            e.preventDefault();
            var serializedData = $(this).serialize();
            $.ajax({
            type: 'POST',
            url: "{% url 'aiuts:dashboard' %}",
            data: serializedData,
            success: function (response) {
            $("#req_payment").trigger('reset');
            table = $("table", response).html();
            $("table").replaceWith(`<table class='table'>` + table + `</table>`);
            alert = `<ul class="messages">
                <div class="position-fixed bg-white border font-weight-bold border-dark alert alert-white alert-dismissible fade show" style="top: 10px; right: 1vw;" role="alert">
                    Updated!
                    <a type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </a>
                </div>

            </ul>`;
            $(".messages").hide();
            $("body").append(alert);
            setTimeout(function() {$(".messages").hide()}, 2000)

            },
            error: function(response) {

            }
            })
            })
            function fetchdata(){
            $.ajax({
            url: '{% url 'aiuts:dashboard' %}',
            type: 'GET',
            success: function(data){
            balance = $("#curr_balance", data).text();
            table = $("table", data).html();
            console.log(balance);
            $("table").replaceWith("<table class='table'>" + table + "</table>");
            $("#curr_balance").text(balance);
            $("#empty").remove();
            alert = `<ul class="messages">
                <div class="position-fixed bg-white border font-weight-bold border-dark alert alert-white alert-dismissible fade show" style="top: 10px; right: 1vw;" role="alert">
                    Updated!
                    <a type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </a>
                </div>

            </ul>`;
            setTimeout(function() {$(".messages").hide()}, 2000)
            },
            complete:function(data){
            setTimeout(fetchdata,5000);
            }
            });
            }

            $(document).ready(function(){
            setTimeout(fetchdata,5000);
            });

        {% endblock %}

aiuts/templates/aiuts/admin_dash.html
{% extends "aiuts/base.html" %}
{% block currPage %} <a href="{% url 'aiuts:index' %}"> Index </a> > Dashboard {% endblock %}
{% block title %} Dashboard {% endblock %}
{% block mainbody %}

	<hr />
	<p style="float: left"> <b>Acc ID:</b> {{ user.acc_id}} </p>
	<p style="float: right"> <b>Balance:</b> {{ user.balance | floatformat:2 }} Baht </p>
	</div>
	<br />
	<h2 class="margin-top"> Deposit Money </h2>
	<hr />
	<form action="{% url 'aiuts:depositmoney' %}" method="post">
		{% csrf_token %}
		<div class="form-group">
		<input type="hidden" name="acc_id" value="{{ user.acc_id }}" />
		<label> Amount: </label>
		<input class="form-control" step="0.01" required="required" type="number" name="amount">
		<label> Password: </label>
		<input class="form-control" required="required" type="password" name="password" />

		<input class="btn my-2 btn-outline-primary" type="submit" value="Deposit">
		</div>

	</form>
	<h2 class="margin-top"> Pending Transaction </h2>
	<hr />
	{% if all_transaction %}
	<table class="table">
		<tr> 
			<th scope="col"> Date </th scope="col">
			<th scope="col"> Finance Controller </th scope="col">
			<th scope="col"> Amount </th scope="col">
			<th scope="col"> Recipient </th scope="col">
	
			<th scope="col"> Action </th>
		</tr>
		</thead>
		<tbody>
	{% endif %}
	{% for transaction in all_transaction %}
	<tr>
		<th scope="row"> {{ transaction.record_date }} </th>
		<td>{% if transaction.sender.acc_id == user %} You {% else %} {{ transaction.sender.acc_id }} {% endif %} </td>
		<td> {{ transaction.amount|floatformat:2}} Baht </td>
		<td>{% if transaction.recipient.acc_id == user %} You {% else %} {{ transaction.recipient.acc_id }} {% endif %} </td>
	
		<td> <a href="{% url 'aiuts:approvetransaction' transaction.id %}"> Approve </a> | <a href="{% url 'aiuts:declinetransaction' transaction.id %}" class="text-danger"> Decline </a> </td>
	</tr>
	{% empty %}
	No pending top up request!
	{% endfor %}
		</tbody>
	</table>


	<h2 class="margin-top"> Get Summary's Transaction </h2>
	<hr />
	<a href="{% url 'aiuts:transactionsummary' %}"> Open Summary of Transaction </a>



	

{% endblock %}

aiuts/templates/aiuts/index.html
{% extends "aiuts/base.html" %}

{% block mainbody %}
	<h2> Actions </h2>
	<hr />
	<ul>
		<li> 
		 <a href="{% url 'aiuts:signup' %}">Sign up for account </a>	
		</li>

	
		<li>
			 <a href="{% url 'aiuts:dashboard' %}">Open Dashboard</a>
		</li>


	</ul>

		<h2 class="mt-2"> Current Accounts </h2>
		<hr />
			{% if all_user %}
		<ul>
			{% for user in all_user %}
				<li>{{ user.acc_id }}  </li>
			{% endfor %}
		</ul>
	{% else %}
		<p> No accounts are available. </p>
	{% endif %}
	<h2 class="mt-1"> Group Members: </h2>
	<hr />
	<ul>
		<li> Andreas </li>
		<li> Broset </li>
		<li> Bryan </li>
		<li> Yilin </li>
	</ul>
	<h2 class="mt-1"> Changelog: </h2>
	<hr />
	<ul>
		<li> Registration </li>
		<li> Login </li>
		<li> Check balance </li>
		<li> Open dashboard (bypassable) </li>
		<li> Check account summary </li>
		<li> Send money </li>
		<li> Remove Url bypass </li>

	</ul>

{% endblock %}

{% block goback %}
{% endblock %}

aiuts/templates/aiuts/send_money.html
{% extends "aiuts/base.html" %}
{% block currPage %} <a href="{% url 'aiuts:index' %}"> Index </a> > Send Money {% endblock %}
{% block title %} Send Money {% endblock %}

{% block mainbody %}
	<h2 class="margin-top"> Send Money </h2>
	<hr />
	<form action="{% url 'aiuts:sendmoney' %}" method="post">
		{% csrf_token %}
		<div class="form-group">
			<label> Your Acc ID </label>
			<input type="text" class="form-control" name="source" />
			<label> Recipient Acc_id: </label>
			<input required="required" type="text" class="form-control" name="destination" placeholder="asdf2323r234rawf23f">
			<label> Amount: </label>
			<input class="form-control" required="required" type="number" step="0.01" min="0.01" max="{{ user.balance }}" name="amount">
		</div>
				<div class="form-group">
			<label for="password">Password: </label>
			<input required="required" class="form-control" type="password" name="password" />
		</div>
		<label> Remark: </label>
		<textarea name="remark" class="form-control"></textarea>
	
		<input type="submit" value="Send" class="btn btn-outline-primary my-1">
	</form>
{% endblock %}

aiuts/templates/aiuts/top_up.html
{% extends "aiuts/base.html" %}
{% block currPage %} <a href="{% url 'aiuts:index' %}"> Index </a> > <a href="{% url 'aiuts:dashboard' %}">Dashboard</a> > Top Up {% endblock %}
{% block title %} Top Up {% endblock %}
{% block mainbody %}
    <main id="topup-page">
    <hr />
    <div>
        <p style="float: left"> <b>Acc ID:</b> {{ user.acc_id}} </p>
        <div />
            <p style="float: right"> <b>Balance:</b> <span id="curr_balance">{{ user.balance | floatformat:2 }}</span> Baht </p>
        </div>
        <br />
        <h2 class="margin-top"> Pending Transactions </h2>
        <hr />
        {% if all_transaction %}
            <table class="table" id="my_topups">
                <tr> 
                    <th scope="col"> Date </th scope="col">
                    <th scope="col"> Recipient </th scope="col">
                    <th scope="col"> Amount </th scope="col">
                    <th scope="col"> Type of Transaction</th>
                    <th scope="col"> Completion </th>
                </tr>
                </thead>
                <tbody>
                {% endif %}
                {% for transaction in all_transaction %}
                    <tr>
                        <th scope="row"> {{ transaction.record_date }} </th>
                    <td>{% if transaction.recipient.user.username == request.user.username %} You {% else %} {{ transaction.recipient.user.username }} {% endif %} </td>
                    <td> {{ transaction.amount|floatformat:2}} Baht </td>
                    <td>{{transaction.type}}</td>
                <td>{% if transaction.recipient.user.username == request.user.username %} {{ transaction.complete }} {% else  %} <a href="{% url 'aiuts:approvetransaction' transaction.id %}"> Approve </a> | <a href="{% url 'aiuts:declinetransaction' transaction.id %}" class="text-danger"> Decline </a>{% endif %} </td>
                    </tr>
                {% empty %}
                    <table id="my_topups"></table>
                    <span id="empty">No pending top up request!</span>
                {% endfor %}
                </tbody>
            </table>
    </main>

            {% if request.user.username != "bank" %}
                <h2 class="margin-top"> Top Up </h2>
                <hr />
                <form id="topup-form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-outline-primary" value="Submit" />
                </form>

                <script src="https://unpkg.com/dayjs@1.8.21/dayjs.min.js"></script>
                <script>dayjs().format()</script>

            {% endif %}

        {% endblock %}
        {% block script %}
            {% if request.user.username != "bank" %}
            $("#topup-form").submit(function (e) {
            e.preventDefault();
            var serializedData = $(this).serialize();
            $.ajax({
            type: 'POST',
            url: "{% url 'aiuts:topup_req' %}",
            data: serializedData,
            success: function (response) {
            $("#topup-form").trigger('reset');
            $("#id_amount").focus();

            var instance = JSON.parse(response["instance"]);
            var topup = instance[0]["fields"];
            $("#my_topups").append(`
            <tr>
                <th>${dayjs().format('MMMM D, YYYY, h:mm a.')||""}</th>     
                <td>${"You"}</td>
                <td>${topup["amount"] + " Baht"||""}</td>
                <td>${topup["type"]}</td>
                <td>${"False"}</td>
            </tr>
            `)
  alert = `<ul class="messages">
                    <div class="position-fixed bg-white border font-weight-bold border-dark alert alert-white alert-dismissible fade show" style="top: 10px; right: 1vw;" role="alert">
                        Requesting money!
                        <a type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </a>
                    </div>

            </ul>`;
            $(".messages").hide();
            $("body").append(alert);
            setTimeout(function() {$(".messages").hide()}, 2000)
           
            },
            error: function(response) {
            alert(response["responseJSON"]["error"]);
            }

            })
            })
            {% endif %}

            function fetchdata(){
            $.ajax({
            url: '{% url 'aiuts:topup_req' %}',
            type: 'GET',
            success: function(data){
            balance = $("#curr_balance", data).text();
            table = $("table", data).html(); 
            $("#curr_balance").text(balance);
            $("#empty").remove();
            $("#my_topups").replaceWith(`<table class='table'>`+table+ `</table>`);
            console.log("updated");
           },
            complete:function(data){
            setTimeout(fetchdata,5000);
            }
            });
            }

            $(document).ready(function(){
            setTimeout(fetchdata,5000);
            });

        {% endblock %}